/**
 * BedWars glyph cosmetics. Each entry carries a name, a rarity, and a cost
 * (a plain Bed Wars Token amount as a number, or a source string for event
 * shop and special acquisitions).
 */

import { BedWarsCosmetic } from "./types";

export const BEDWARS_GLYPHS: readonly BedWarsCosmetic[] = [
  { name: "Iron", rarity: "COMMON", cost: 5000 },
  { name: "Gold", rarity: "COMMON", cost: 5000 },
  { name: "Diamond", rarity: "COMMON", cost: 5000 },
  { name: "Emerald", rarity: "COMMON", cost: 5000 },
  { name: "Thumbs Down", rarity: "COMMON", cost: 5000 },
  { name: "Thumbs Up", rarity: "COMMON", cost: 5000 },
  { name: "Hi", rarity: "COMMON", cost: 5000 },
  { name: "Storm", rarity: "COMMON", cost: 5000 },
  { name: "Sword", rarity: "COMMON", cost: 5000 },
  { name: "Yes", rarity: "COMMON", cost: 5000 },
  { name: "Burn", rarity: "COMMON", cost: 5000 },
  { name: "Daisy", rarity: "COMMON", cost: 5000 },
  { name: "No", rarity: "COMMON", cost: 5000 },
  { name: "Bronze Shield", rarity: "COMMON", cost: 5000 },
  { name: "Silver Shield", rarity: "COMMON", cost: 5000 },
  { name: "Gold Shield", rarity: "COMMON", cost: 5000 },
  { name: "Star", rarity: "COMMON", cost: 5000 },
  {
    name: "Candy Cane",
    rarity: "COMMON",
    cost: "15,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Christmas Tree",
    rarity: "COMMON",
    cost: "15,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Gift",
    rarity: "COMMON",
    cost: "15,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Bunny",
    rarity: "COMMON",
    cost: "15,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Big Smile",
    rarity: "COMMON",
    cost: "15,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Chick",
    rarity: "COMMON",
    cost: "15,000 (Easter only)/Easter Event Shop",
  },
  { name: "Celebration Popper", rarity: "COMMON", cost: 5000 },
  { name: "Lantern", rarity: "COMMON", cost: 5000 },
  { name: "Pig", rarity: "COMMON", cost: 5000 },
  { name: "Squeak", rarity: "COMMON", cost: 5000 },
  { name: "Lion Dancer", rarity: "COMMON", cost: 5000 },
  { name: "Bed", rarity: "RARE", cost: 10000 },
  { name: "GG", rarity: "RARE", cost: 10000 },
  { name: "Smiley Face", rarity: "RARE", cost: 10000 },
  { name: "Spectrum", rarity: "RARE", cost: 10000 },
  { name: "Lol", rarity: "RARE", cost: 10000 },
  { name: "TNT", rarity: "RARE", cost: 10000 },
  {
    name: "Ghostly Ghost",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Hall-o-ween",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Spider",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Evil Pumpkin",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Cute Pumpkin",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  { name: "Grave", rarity: "RARE", cost: "Halloween Event Shop" },
  {
    name: "Super Snow Golem",
    rarity: "RARE",
    cost: "30,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Gingerbread Man",
    rarity: "RARE",
    cost: "30,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Holly",
    rarity: "RARE",
    cost: "30,000 (Holidays only)/Holidays Event Shop",
  },
  { name: "Bauble", rarity: "RARE", cost: "Holidays Event Shop" },
  { name: "Pilgrim Hat", rarity: "RARE", cost: "Holidays Event Shop" },
  {
    name: "Quack",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Bloom",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Bunny Guy",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Party",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Hot Cross Bun",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Easter Flower",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Carrot",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  { name: "Blossom", rarity: "RARE", cost: 10000 },
  { name: "Orange", rarity: "RARE", cost: 10000 },
  { name: "Earth", rarity: "RARE", cost: 10000 },
  { name: "Sparkle", rarity: "RARE", cost: 10000 },
  { name: "Lunar Gold", rarity: "RARE", cost: 10000 },
  { name: "Lucky Rabbit", rarity: "RARE", cost: 10000 },
  { name: "Coconut", rarity: "RARE", cost: "Summer Event Shop" },
  { name: "Flame", rarity: "RARE", cost: "Summer Event Shop" },
  { name: "Shell", rarity: "RARE", cost: "Summer Event Shop" },
  { name: "Heart", rarity: "EPIC", cost: 25000 },
  { name: "Angry Face", rarity: "EPIC", cost: 25000 },
  { name: "Creeper Scream", rarity: "EPIC", cost: 25000 },
  { name: "Skull", rarity: "EPIC", cost: 25000 },
  { name: "Shock Face", rarity: "EPIC", cost: 25000 },
  { name: "Winky Face", rarity: "EPIC", cost: 25000 },
  { name: "Scream Face", rarity: "EPIC", cost: 25000 },
  {
    name: "Bat",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Candy",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Eyeball",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Witch Hat",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Candy Corn",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  { name: "Black Cat", rarity: "EPIC", cost: "Halloween Event Shop" },
  { name: "Cauldron", rarity: "EPIC", cost: "Halloween Event Shop" },
  {
    name: "Hype the Elf",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Santa Hat",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Dreidel",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Menorah",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Snowflake",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  { name: "Festive Bell", rarity: "EPIC", cost: "Holidays Event Shop" },
  {
    name: "Easter Egg",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Chocolate Egg",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Egg Basket",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Rabbit",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  { name: "Dog", rarity: "EPIC", cost: 25000 },
  { name: "Dragon", rarity: "EPIC", cost: 25000 },
  { name: "Rose", rarity: "EPIC", cost: 25000 },
  { name: "Mouse", rarity: "EPIC", cost: 25000 },
  { name: "Fai Chun", rarity: "EPIC", cost: 25000 },
  { name: "Red Envelope", rarity: "EPIC", cost: 25000 },
  { name: "Strawberry", rarity: "EPIC", cost: "Summer Event Shop" },
  { name: "Palm Tree", rarity: "EPIC", cost: "Summer Event Shop" },
  { name: "HOT", rarity: "EPIC", cost: "Summer Event Shop" },
  { name: "Umbrella", rarity: "EPIC", cost: "Summer Event Shop" },
  { name: "Cry Face", rarity: "LEGENDARY", cost: 100000 },
  { name: "#1", rarity: "LEGENDARY", cost: 100000 },
  { name: "RIP", rarity: "LEGENDARY", cost: 100000 },
  { name: "Chicken", rarity: "LEGENDARY", cost: 100000 },
  { name: "Rainbow", rarity: "LEGENDARY", cost: 100000 },
  {
    name: "Evil Kitty",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Very Evil Pumpkin",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Cute Ghost",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Reindeer",
    rarity: "LEGENDARY",
    cost: "300,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Stocking",
    rarity: "LEGENDARY",
    cost: "300,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Wreath",
    rarity: "LEGENDARY",
    cost: "300,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Chocolate",
    rarity: "LEGENDARY",
    cost: "300,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "This is Fine",
    rarity: "LEGENDARY",
    cost: "300,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Egg with Bow",
    rarity: "LEGENDARY",
    cost: "300,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Sunflower",
    rarity: "LEGENDARY",
    cost: "300,000 (Easter only)/Easter Event Shop",
  },
  { name: "Chinese Firecracker", rarity: "LEGENDARY", cost: 100000 },
  { name: "Moon", rarity: "LEGENDARY", cost: 100000 },
  { name: "Tiger", rarity: "LEGENDARY", cost: 100000 },
  { name: "Player Face", rarity: "LEGENDARY", cost: "Slumber Hotel" },
];

