/**
 * BedWars island toppers: decorative cosmetics displayed atop a player's island.
 * Each entry carries a name, rarity, and cost (a Bed Wars Token amount as a
 * number, or a source string for event shops, challenges, battle passes, etc.).
 */

import { BedWarsCosmetic } from "./types";

export const BEDWARS_ISLAND_TOPPERS: readonly BedWarsCosmetic[] = [
  { name: "Note", rarity: "COMMON", cost: 5000 },
  { name: "Sheep", rarity: "COMMON", cost: 5000 },
  { name: "Slime", rarity: "COMMON", cost: 5000 },
  { name: "TNT", rarity: "COMMON", cost: 5000 },
  { name: "Tree", rarity: "COMMON", cost: 5000 },
  { name: "Flame", rarity: "COMMON", cost: 5000 },
  { name: "Heart", rarity: "COMMON", cost: 5000 },
  {
    name: "Candy Cane",
    rarity: "COMMON",
    cost: "15,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Fancy Santa Hat",
    rarity: "COMMON",
    cost: "15,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Bunch of Presents",
    rarity: "COMMON",
    cost: "15,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Comet the Reindeer",
    rarity: "COMMON",
    cost: "15,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Bunny",
    rarity: "COMMON",
    cost: "15,000 (Easter only)/Easter Event Shop",
  },
  { name: "Firework Rocket", rarity: "COMMON", cost: 5000 },
  { name: "Fountain Firework", rarity: "COMMON", cost: 5000 },
  { name: "Mark of the Paw", rarity: "COMMON", cost: 5000 },
  { name: "Year of the Pig", rarity: "COMMON", cost: 5000 },
  { name: "Sword", rarity: "RARE", cost: 10000 },
  { name: "Bomb", rarity: "RARE", cost: 10000 },
  { name: "Gong", rarity: "RARE", cost: 10000 },
  { name: "Smiley Face", rarity: "RARE", cost: 10000 },
  { name: "Rubix Cube", rarity: "RARE", cost: 10000 },
  { name: "Brick House", rarity: "RARE", cost: 10000 },
  {
    name: "Candle",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Ghost",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Sinister Pot",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Thunder",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Gargoyle",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Suspicious Tree",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Wicked Z-type",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Boo!",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Gravestone",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Witch's Potion",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Spooky Lantern",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Wingless Angel",
    rarity: "RARE",
    cost: "30,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Robin",
    rarity: "RARE",
    cost: "30,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Basket",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Carrot",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Easter Bell",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  { name: "Yin and Yang", rarity: "RARE", cost: 10000 },
  { name: "Cherry Blossom", rarity: "RARE", cost: 10000 },
  { name: "Temple", rarity: "RARE", cost: 10000 },
  { name: "Lantern", rarity: "RARE", cost: 10000 },
  { name: "Candles", rarity: "RARE", cost: 10000 },
  { name: "Firecracker", rarity: "RARE", cost: 10000 },
  { name: "Assassin", rarity: "RARE", cost: '"Assassin" Bed Wars Challenge' },
  {
    name: "Shopping Cart",
    rarity: "RARE",
    cost: '"Regular Shopper" Bed Wars Challenge',
  },
  {
    name: "Invisible Villager",
    rarity: "RARE",
    cost: '"Invisible Shop" Bed Wars Challenge',
  },
  {
    name: "Snowflake",
    rarity: "RARE",
    cost: "30,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Leaf",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Sapling",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  { name: "Surfboard", rarity: "RARE", cost: "Summer Event Shop" },
  { name: "Wave", rarity: "RARE", cost: "Summer Event Shop" },
  { name: "Big Present", rarity: "RARE", cost: "Holidays Event Shop" },
  { name: "Gingerbread House", rarity: "RARE", cost: "Holidays Event Shop" },
  { name: "Stocking", rarity: "RARE", cost: "Holidays Event Shop" },
  { name: "Pudding", rarity: "RARE", cost: "Holidays Event Shop" },
  { name: "Tall Carrot", rarity: "RARE", cost: 10000 },
  { name: "Rain Cloud", rarity: "RARE", cost: "Easter Event Shop" },
  { name: "Sprout", rarity: "RARE", cost: "Easter Event Shop" },
  { name: "Watermelon", rarity: "RARE", cost: "Summer Event Shop" },
  { name: "Spooky Hypixel", rarity: "RARE", cost: "Halloween Event Shop" },
  { name: "Pinecone", rarity: "RARE", cost: "Holidays Event Shop" },
  { name: "Nest of Chicks", rarity: "RARE", cost: "Easter Event Shop" },
  { name: "Mister Egg", rarity: "RARE", cost: "Easter Event Shop" },
  { name: "Fishing Rod", rarity: "RARE", cost: "Summer Event Shop" },
  { name: "Bungalow", rarity: "RARE", cost: "Summer Event Shop" },
  { name: "Owl", rarity: "RARE", cost: "Halloween Event Shop" },
  { name: "Birdhouse", rarity: "RARE", cost: "Easter Event Shop" },
  { name: "Picnic Basket", rarity: "RARE", cost: "Easter Event Shop" },
  { name: "Watering Can", rarity: "RARE", cost: "Easter Event Shop" },
  { name: "Rainbow Sheep", rarity: "EPIC", cost: 25000 },
  { name: "Sunglasses", rarity: "EPIC", cost: 25000 },
  { name: "Treasure Chest", rarity: "EPIC", cost: 25000 },
  { name: "Fish Bowl", rarity: "EPIC", cost: 25000 },
  { name: "Sloth", rarity: "EPIC", cost: 25000 },
  { name: "Monocle", rarity: "EPIC", cost: 25000 },
  {
    name: "Clown",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Happy Pumpkin",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Mini Herobrine's Mansion",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Candy Corn",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Candy Basket",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Frankenstein",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Mummy",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Devil",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Witch's House",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Magic Snowglobe",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Bell",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Penguin",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Easter Egg",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Rabbit Ears",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Chocolate Egg",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Sunflower",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  { name: "Temple Hut", rarity: "EPIC", cost: 25000 },
  { name: "Ox", rarity: "EPIC", cost: 25000 },
  { name: "Red Envelope", rarity: "EPIC", cost: 25000 },
  { name: "Gapple", rarity: "EPIC", cost: "Battle Pass: Season 1" },
  { name: "Skullsword", rarity: "EPIC", cost: "Battle Pass: Season 1" },
  {
    name: "Collector's Chest",
    rarity: "EPIC",
    cost: '"Collector" Bed Wars Challenge',
  },
  {
    name: "Toxic Rain",
    rarity: "EPIC",
    cost: '"Toxic Rain" Bed Wars Challenge',
  },
  {
    name: "Lazy Miner",
    rarity: "EPIC",
    cost: '"Lazy Miner" Bed Wars Challenge',
  },
  {
    name: "Dreidel",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Gold Present",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  { name: "Penjing", rarity: "EPIC", cost: 25000 },
  { name: "Tiger", rarity: "EPIC", cost: 25000 },
  {
    name: "Ladybug",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  { name: "Parasol", rarity: "EPIC", cost: "Summer Event Shop" },
  { name: "Chocolate Bar", rarity: "EPIC", cost: "Halloween Event Shop" },
  { name: "Chimney", rarity: "EPIC", cost: "Holidays Event Shop" },
  { name: "Small Rabbit", rarity: "EPIC", cost: 25000 },
  { name: "Cow", rarity: "EPIC", cost: "Easter Event Shop" },
  { name: "Party Sloth", rarity: "EPIC", cost: "Anniversary Bingo" },
  { name: "Crab", rarity: "EPIC", cost: "Summer Event Shop" },
  { name: "Eyeball", rarity: "EPIC", cost: "Halloween Event Shop" },
  { name: "Snowy Cabin", rarity: "EPIC", cost: "Holidays Event Shop" },
  { name: "Panda", rarity: "EPIC", cost: 25000 },
  { name: "Pagoda", rarity: "EPIC", cost: 25000 },
  { name: "Coconut Drink", rarity: "EPIC", cost: "Summer Event Shop" },
  { name: "Cyclops", rarity: "EPIC", cost: "Halloween Event Shop" },
  { name: "Witch", rarity: "EPIC", cost: "Halloween Event Shop" },
  { name: "Hot Cocoa", rarity: "EPIC", cost: "Holidays Event Shop" },
  { name: "Roast Turkey", rarity: "EPIC", cost: "Holidays Event Shop" },
  { name: "Penguin Stack", rarity: "EPIC", cost: "Holidays Event Shop" },
  { name: "Snake", rarity: "EPIC", cost: 25000 },
  { name: "Hermit Crab", rarity: "EPIC", cost: "Summer Event Shop" },
  { name: "Sailboat", rarity: "EPIC", cost: "Summer Event Shop" },
  { name: "Chicken", rarity: "LEGENDARY", cost: 100000 },
  { name: "Top Hat", rarity: "LEGENDARY", cost: 100000 },
  { name: "Whale", rarity: "LEGENDARY", cost: 100000 },
  { name: "Fancy Helmet", rarity: "LEGENDARY", cost: 100000 },
  {
    name: "Tournament Position",
    rarity: "LEGENDARY",
    cost: "Tournament Hall (50 Tributes)",
  },
  {
    name: "Parchment the Skelly",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Witch Hat",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Skeleton Thumbs Up",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Werewolf",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Reaper",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "L",
    rarity: "LEGENDARY",
    cost: "300,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Humongous Christmas Tree",
    rarity: "LEGENDARY",
    cost: "300,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Sleigh",
    rarity: "LEGENDARY",
    cost: "300,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Snowman",
    rarity: "LEGENDARY",
    cost: "300,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Hatching Egg",
    rarity: "LEGENDARY",
    cost: "300,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Tulips",
    rarity: "LEGENDARY",
    cost: "300,000 (Easter only)/Easter Event Shop",
  },
  { name: "Lunar Dragon", rarity: "LEGENDARY", cost: 100000 },
  { name: "Dragon Head", rarity: "LEGENDARY", cost: 100000 },
  {
    name: "Champion's Chalice",
    rarity: "LEGENDARY",
    cost: "Battle Pass: Season 1",
  },
  {
    name: "Heartbleed",
    rarity: "LEGENDARY",
    cost: '"Ultimate UHC" Bed Wars Challenge',
  },
  {
    name: "Magic Bunny",
    rarity: "LEGENDARY",
    cost: '"Sleight of Hand" Bed Wars Challenge',
  },
  {
    name: "Ballista",
    rarity: "LEGENDARY",
    cost: '"Marksman" Bed Wars Challenge',
  },
  {
    name: "Traffic Light",
    rarity: "LEGENDARY",
    cost: '"Red Light, Green Light" Bed Wars Challenge',
  },
  {
    name: "Assassin's Blade",
    rarity: "LEGENDARY",
    cost: '"Master Assassin" Bed Wars Challenge',
  },
  {
    name: "Presidential Goons",
    rarity: "LEGENDARY",
    cost: '"Protect The President" Bed Wars Challenge',
  },
  {
    name: "Nutcracker",
    rarity: "LEGENDARY",
    cost: "300,000 (Holidays only)/Holidays Event Shop",
  },
  { name: "Ramen", rarity: "LEGENDARY", cost: 100000 },
  {
    name: "Bee",
    rarity: "LEGENDARY",
    cost: "300,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Bluebird",
    rarity: "LEGENDARY",
    cost: "300,000 (Easter only)/Easter Event Shop",
  },
  { name: "Demon", rarity: "LEGENDARY", cost: "Halloween Event Shop" },
  { name: "Zombie Hand", rarity: "LEGENDARY", cost: "Halloween Event Shop" },
  { name: "Large Rabbit", rarity: "LEGENDARY", cost: 100000 },
  { name: "Hypixel Knight", rarity: "LEGENDARY", cost: "Anniversary Bingo" },
  { name: "Sand Castle", rarity: "LEGENDARY", cost: "Summer Event Shop" },
  { name: "Chocolate Bunny", rarity: "LEGENDARY", cost: "Easter Event Shop" },
  { name: "Flamingo", rarity: "LEGENDARY", cost: "Summer Event Shop" },
];

