import { BedWarsCosmetic } from "./types";

/**
 * Bed Wars sprays cosmetics reference data.
 *
 * Each entry records the spray name, its rarity, and its cost. Plain Bed Wars
 * Token amounts are stored as numbers; event shop, rank, and other special
 * costs are kept as their original source strings. "Hypixel Logo" has no cost
 * shown and uses an empty string.
 */
export const BEDWARS_SPRAYS: readonly BedWarsCosmetic[] = [
  { name: "Hypixel Logo", rarity: "COMMON", cost: "" },
  { name: "Creeper", rarity: "COMMON", cost: 5000 },
  { name: "Thanks", rarity: "COMMON", cost: 5000 },
  { name: "Diamond", rarity: "COMMON", cost: 5000 },
  { name: "Invisibility Potion", rarity: "COMMON", cost: 5000 },
  {
    name: "Disco Pumpkin",
    rarity: "COMMON",
    cost: "15,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Reveillon",
    rarity: "COMMON",
    cost: "15,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Christmas Tree",
    rarity: "COMMON",
    cost: "15,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Careful Santa",
    rarity: "COMMON",
    cost: "15,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Easter Eggs",
    rarity: "COMMON",
    cost: "15,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Bunny GG",
    rarity: "COMMON",
    cost: "15,000 (Easter only)/Easter Event Shop",
  },
  { name: "Fireworks", rarity: "COMMON", cost: 5000 },
  { name: "Year of the Dog", rarity: "COMMON", cost: 5000 },
  { name: "Year of the Pig", rarity: "COMMON", cost: 5000 },
  { name: "Lantern", rarity: "COMMON", cost: 5000 },
  { name: "Year of the Rat", rarity: "COMMON", cost: 5000 },
  { name: "Year of the Ox", rarity: "COMMON", cost: 5000 },
  { name: "Lion Dancer", rarity: "COMMON", cost: 5000 },
  { name: "Year of the Tiger", rarity: "COMMON", cost: 5000 },
  { name: "Year of the Rabbit", rarity: "COMMON", cost: 5000 },
  { name: "Year of the Dragon", rarity: "COMMON", cost: 5000 },
  { name: "Year of the Snake", rarity: "COMMON", cost: 5000 },
  { name: "Bed Shield", rarity: "RARE", cost: 10000 },
  { name: "GG WP", rarity: "RARE", cost: 10000 },
  { name: "Sorry", rarity: "RARE", cost: 10000 },
  { name: "Enderman", rarity: "RARE", cost: 10000 },
  { name: "Golem Riding", rarity: "RARE", cost: 10000 },
  { name: "Leaping Potion", rarity: "RARE", cost: 10000 },
  {
    name: "Sir von Mewrtimer",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Defenestration",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Boo!",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Perfect Sword Throw",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "FaBOOlous",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Found U",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Snowball Fight",
    rarity: "RARE",
    cost: "30,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Merry Base",
    rarity: "RARE",
    cost: "30,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Surprise Snowball",
    rarity: "RARE",
    cost: "30,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Angry Turkey",
    rarity: "RARE",
    cost: "30,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Santa Slips",
    rarity: "RARE",
    cost: "30,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Easter Creeper",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "The Great Egg Hunt",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Easter Basket",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Egg Hunt",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Rabbit Costume",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  { name: "Dragon", rarity: "RARE", cost: 10000 },
  { name: "Pig Peace", rarity: "RARE", cost: 10000 },
  { name: "Angry Cow", rarity: "RARE", cost: 10000 },
  {
    name: "Egg Gunner",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Egg Hit",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Rabbits in a Basket",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Pumpkinz",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Sweets",
    rarity: "RARE",
    cost: "30,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Snow Angel",
    rarity: "RARE",
    cost: "30,000 (Holidays only)/Holidays Event Shop",
  },
  { name: "Good Fortune", rarity: "RARE", cost: 10000 },
  {
    name: "Bunny Parkour",
    rarity: "RARE",
    cost: "30,000 (Easter only)/Easter Event Shop",
  },
  { name: "Lucky Rabbit", rarity: "RARE", cost: 10000 },
  { name: "Spooky Game Over", rarity: "RARE", cost: "Halloween Event Shop" },
  { name: "Season's Greetings", rarity: "RARE", cost: "Holidays Event Shop" },
  { name: "Silent Night", rarity: "RARE", cost: "Holidays Event Shop" },
  {
    name: "Ugly Bed Wars Sweater",
    rarity: "RARE",
    cost: "Holidays Event Shop",
  },
  { name: "Golem Picnic", rarity: "RARE", cost: "Easter Event Shop" },
  { name: "Cooler Climates", rarity: "RARE", cost: "Summer Event Shop" },
  { name: "Comfy Web", rarity: "RARE", cost: "Halloween Event Shop" },
  { name: "Casual Christmas", rarity: "RARE", cost: "Holidays Event Shop" },
  {
    name: "Family Photo (Christmas Edition)",
    rarity: "RARE",
    cost: "Holidays Event Shop",
  },
  { name: "Flowers For You", rarity: "RARE", cost: 10000 },
  { name: "Lazy Spring", rarity: "RARE", cost: 10000 },
  { name: "Sand Castle", rarity: "RARE", cost: 10000 },
  { name: "Bed Breaker", rarity: "EPIC", cost: 25000 },
  { name: "I Love You", rarity: "EPIC", cost: 25000 },
  { name: "Bye Bye", rarity: "EPIC", cost: 25000 },
  { name: "TNT Drop", rarity: "EPIC", cost: 25000 },
  {
    name: "Candy King",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Groovy the Ghost",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Starry Veggie",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Witch Bouillon",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Fake Vampire",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Scared",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Garlic",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Witch Please",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Mob Party",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Festive Harbinger",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Sleep Well",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Snowball Spammer",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Puppy Surprise",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Sniper Snowball",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Wrong Eggs",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Egg Surprise",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Golden Egg",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  { name: "Dogs of Wisdom", rarity: "EPIC", cost: 25000 },
  { name: "Peaceful", rarity: "EPIC", cost: 25000 },
  { name: "Smug Pig", rarity: "EPIC", cost: 25000 },
  { name: "Earth Pig", rarity: "EPIC", cost: 25000 },
  { name: "Rat Costume", rarity: "EPIC", cost: 25000 },
  { name: "Rats 2020", rarity: "EPIC", cost: 25000 },
  { name: "Curled Ox", rarity: "EPIC", cost: 25000 },
  {
    name: "Cute Bunny",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Egg Time",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Distinguished Ghost",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Spooky Skelington",
    rarity: "EPIC",
    cost: "75,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Menorah",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Mistletoe",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Snow Jerry",
    rarity: "EPIC",
    cost: "75,000 (Holidays only)/Holidays Event Shop",
  },
  { name: "Sleeps and Treats", rarity: "EPIC", cost: 25000 },
  {
    name: "Easter Sweater",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Egg Decorations",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  {
    name: "Lazy Bunnies",
    rarity: "EPIC",
    cost: "75,000 (Easter only)/Easter Event Shop",
  },
  { name: "Rabbit Celebration", rarity: "EPIC", cost: 25000 },
  { name: "Bunny Lantern", rarity: "EPIC", cost: 25000 },
  {
    name: "Monster Under the Bed",
    rarity: "EPIC",
    cost: "Halloween Event Shop",
  },
  { name: "Party Crasher", rarity: "EPIC", cost: "Halloween Event Shop" },
  { name: "Pumpkin Farm", rarity: "EPIC", cost: "Halloween Event Shop" },
  { name: "Gingerbread Jerry", rarity: "EPIC", cost: "Holidays Event Shop" },
  { name: "One of Us", rarity: "EPIC", cost: "Easter Event Shop" },
  { name: "Buff Chicken", rarity: "EPIC", cost: "Easter Event Shop" },
  { name: "Ice Scream Cart", rarity: "EPIC", cost: "Summer Event Shop" },
  { name: "Jerry Island Poster", rarity: "EPIC", cost: "Summer Event Shop" },
  {
    name: "Undead Lifesaving Association",
    rarity: "EPIC",
    cost: "Summer Event Shop",
  },
  { name: "Gothic Jerry", rarity: "EPIC", cost: "Halloween Event Shop" },
  { name: "Haunted Conscience", rarity: "EPIC", cost: "Halloween Event Shop" },
  { name: "Angelic Jerry", rarity: "EPIC", cost: "Holidays Event Shop" },
  { name: "Turkey Day", rarity: "EPIC", cost: "Holidays Event Shop" },
  { name: "Bee That Chicken", rarity: "EPIC", cost: 25000 },
  { name: "Painted Dragon Egg", rarity: "EPIC", cost: 25000 },
  { name: "Sea Bass", rarity: "EPIC", cost: 25000 },
  { name: "Sloth Burn", rarity: "EPIC", cost: 25000 },
  { name: "Surfs Up", rarity: "EPIC", cost: 25000 },
  { name: "Carried", rarity: "LEGENDARY", cost: 100000 },
  { name: "Dragon Slayer", rarity: "LEGENDARY", cost: 100000 },
  { name: "Loot Chest", rarity: "LEGENDARY", cost: "Currently unobtainable!" },
  { name: "VIP", rarity: "LEGENDARY", cost: "[VIP]" },
  { name: "VIP+", rarity: "LEGENDARY", cost: "[VIP+]" },
  { name: "MVP", rarity: "LEGENDARY", cost: "[MVP]" },
  { name: "MVP+", rarity: "LEGENDARY", cost: "[MVP+]" },
  {
    name: "Doot Doot",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "GG WPumpkin",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Skeleton Says Hi",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Watcher",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Snowman Rampage",
    rarity: "LEGENDARY",
    cost: "300,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Chocolate Feast",
    rarity: "LEGENDARY",
    cost: "300,000 (Easter only)/Easter Event Shop",
  },
  { name: "Sweet Dreams", rarity: "LEGENDARY", cost: 100000 },
  { name: "Ox Costume", rarity: "LEGENDARY", cost: 100000 },
  {
    name: "Trick or Treat",
    rarity: "LEGENDARY",
    cost: "300,000 (Halloween only)/Halloween Event Shop",
  },
  {
    name: "Candy Cane Sniper",
    rarity: "LEGENDARY",
    cost: "300,000 (Holidays only)/Holidays Event Shop",
  },
  {
    name: "Chickens",
    rarity: "LEGENDARY",
    cost: "300,000 (Easter only)/Easter Event Shop",
  },
  { name: "SaBEEtage", rarity: "LEGENDARY", cost: "Easter Event Shop" },
  { name: "Pumpkin Pals", rarity: "LEGENDARY", cost: "Halloween Event Shop" },
];

